### ISSUE TITLE
ParseMode.NONE uses Markdown V2

### ISSUE THREAD

**Issue by sueskind** [alxnull/tgsend#1]
Hi there,
firstly, thank you for this simple package! I really enjoy using it.

However `ParseMode.NONE` shows unexpected behavior. Since there is an extra option for Markdown V2 the user expects `NONE` to behave like it accepts plain text.

Doing 
```python
for c in "_*[]()~>#+-=|{}.!":
    msg = msg.replace(c, "\\" + c)
```
when choosing `ParseMode.NONE` would correct this.

Or maybe introduce `ParseMode.PLAIN` with this behavior?

**Comment by alxnull** [comment]
Hi @sueskind, glad you like this tool! Your explanation regarding `ParseMode.NONE` makes sense. Would you mind opening a pull request with your suggested fix? (Otherwise, I could also look into it.)

**Comment by sueskind** [comment]
Thank you for still maintaining this project! You can test my pull request with the following snippet:

```python
tg = Telegram(token="12345:ABCDEFG")
res = tg.send_message("Hello _ * [ !", "Title", chat_id=123456, parse_mode=ParseMode.NONE)
res.raise_for_status()
```

In the old version this raised HTTP error 400.

**Comment by alxnull** [comment]
Hey @sueskind, while reviewing your PR, I think I found that your issue is caused by a different part of the code. E.g., instead of your snippet, try running this on the unpatched version:

```python
tg = Telegram(token="12345:ABCDEFG", parse_mode=ParseMode.NONE)
res = tg.send_message("Hello _ * [ !", "Title", chat_id=123456)
res.raise_for_status()
```
This should work even without your fix. This snippet sets the default/ fallback parse mode, which is `MARKDOWN_V2` by default. `ParseMode.NONE` is defined as an empty string, so because of the following faulty line, it will fall back to `MARKDOWN_V2` every time you pass `NONE`:
https://github.com/alxnull/tgsend/blob/d2fa5fec077d3db4c36d029541c577b00a219176/tgsend.py#L154

**Comment by alxnull** [comment]
I've just pushed a fix for the issue I described. Would be awesome if you could check if this resolves the unexpected behavior you found.

**Comment by sueskind** [comment]
Yes, my issue seems fixed now, thank you!

**Comment by alxnull** [comment]
Great. Thanks a lot anyway for looking into this and your PR!
